/**
 * THIS FILE IS AUTO-GENERATED — DO NOT EDIT.
 *
 * Generated by: pnpm db:types
 * Source: local Supabase schema (supabase gen types typescript --local)
 *
 * Re-generate after migration changes:
 *   pnpm db:reset && pnpm db:types
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      audit_logs: {
        Row: {
          action: string
          actor_profile_id: string | null
          actor_role: Database["public"]["Enums"]["staff_role"] | null
          created_at: string
          entity_id: string
          entity_type: string
          id: string
          payload: Json | null
        }
        Insert: {
          action: string
          actor_profile_id?: string | null
          actor_role?: Database["public"]["Enums"]["staff_role"] | null
          created_at?: string
          entity_id: string
          entity_type: string
          id?: string
          payload?: Json | null
        }
        Update: {
          action?: string
          actor_profile_id?: string | null
          actor_role?: Database["public"]["Enums"]["staff_role"] | null
          created_at?: string
          entity_id?: string
          entity_type?: string
          id?: string
          payload?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_profile_id_fkey"
            columns: ["actor_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      categories: {
        Row: {
          created_at: string
          description: string | null
          display_order: number
          id: string
          is_active: boolean
          name: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          display_order?: number
          id?: string
          is_active?: boolean
          name: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          display_order?: number
          id?: string
          is_active?: boolean
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      delivery_attempts: {
        Row: {
          attempted_at: string
          created_at: string
          failure_note: string | null
          failure_reason:
            | Database["public"]["Enums"]["delivery_failure_reason"]
            | null
          id: string
          order_id: string
          route_stop_id: string
          succeeded: boolean
        }
        Insert: {
          attempted_at?: string
          created_at?: string
          failure_note?: string | null
          failure_reason?:
            | Database["public"]["Enums"]["delivery_failure_reason"]
            | null
          id?: string
          order_id: string
          route_stop_id: string
          succeeded: boolean
        }
        Update: {
          attempted_at?: string
          created_at?: string
          failure_note?: string | null
          failure_reason?:
            | Database["public"]["Enums"]["delivery_failure_reason"]
            | null
          id?: string
          order_id?: string
          route_stop_id?: string
          succeeded?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "delivery_attempts_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "delivery_attempts_route_stop_id_fkey"
            columns: ["route_stop_id"]
            isOneToOne: false
            referencedRelation: "route_stops"
            referencedColumns: ["id"]
          },
        ]
      }
      delivery_routes: {
        Row: {
          assigned_delivery_profile_id: string | null
          created_at: string
          id: string
          route_date: string
          service_area_id: string
          status: Database["public"]["Enums"]["delivery_route_status"]
          updated_at: string
        }
        Insert: {
          assigned_delivery_profile_id?: string | null
          created_at?: string
          id?: string
          route_date: string
          service_area_id: string
          status?: Database["public"]["Enums"]["delivery_route_status"]
          updated_at?: string
        }
        Update: {
          assigned_delivery_profile_id?: string | null
          created_at?: string
          id?: string
          route_date?: string
          service_area_id?: string
          status?: Database["public"]["Enums"]["delivery_route_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "delivery_routes_assigned_delivery_profile_id_fkey"
            columns: ["assigned_delivery_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "delivery_routes_service_area_id_fkey"
            columns: ["service_area_id"]
            isOneToOne: false
            referencedRelation: "service_areas"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_balances: {
        Row: {
          available_quantity: number | null
          created_at: string
          id: string
          on_hand_quantity: number
          operational_location_id: string
          reserved_quantity: number
          sku_id: string
          updated_at: string
        }
        Insert: {
          available_quantity?: number | null
          created_at?: string
          id?: string
          on_hand_quantity?: number
          operational_location_id: string
          reserved_quantity?: number
          sku_id: string
          updated_at?: string
        }
        Update: {
          available_quantity?: number | null
          created_at?: string
          id?: string
          on_hand_quantity?: number
          operational_location_id?: string
          reserved_quantity?: number
          sku_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "inventory_balances_operational_location_id_fkey"
            columns: ["operational_location_id"]
            isOneToOne: false
            referencedRelation: "operational_locations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_balances_sku_id_fkey"
            columns: ["sku_id"]
            isOneToOne: false
            referencedRelation: "skus"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_movements: {
        Row: {
          actor_profile_id: string | null
          created_at: string
          id: string
          movement_type: Database["public"]["Enums"]["inventory_movement_type"]
          operational_location_id: string
          quantity_delta: number
          reason: string | null
          reference_id: string | null
          reference_type: string | null
          sku_id: string
        }
        Insert: {
          actor_profile_id?: string | null
          created_at?: string
          id?: string
          movement_type: Database["public"]["Enums"]["inventory_movement_type"]
          operational_location_id: string
          quantity_delta: number
          reason?: string | null
          reference_id?: string | null
          reference_type?: string | null
          sku_id: string
        }
        Update: {
          actor_profile_id?: string | null
          created_at?: string
          id?: string
          movement_type?: Database["public"]["Enums"]["inventory_movement_type"]
          operational_location_id?: string
          quantity_delta?: number
          reason?: string | null
          reference_id?: string | null
          reference_type?: string | null
          sku_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "inventory_movements_actor_profile_id_fkey"
            columns: ["actor_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_operational_location_id_fkey"
            columns: ["operational_location_id"]
            isOneToOne: false
            referencedRelation: "operational_locations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_sku_id_fkey"
            columns: ["sku_id"]
            isOneToOne: false
            referencedRelation: "skus"
            referencedColumns: ["id"]
          },
        ]
      }
      operational_locations: {
        Row: {
          address_line: string
          city: string
          created_at: string
          id: string
          is_active: boolean
          kind: Database["public"]["Enums"]["operational_location_kind"]
          lat: number | null
          lng: number | null
          name: string
          pin_code: string
          state: string
          updated_at: string
        }
        Insert: {
          address_line: string
          city: string
          created_at?: string
          id?: string
          is_active?: boolean
          kind?: Database["public"]["Enums"]["operational_location_kind"]
          lat?: number | null
          lng?: number | null
          name: string
          pin_code: string
          state: string
          updated_at?: string
        }
        Update: {
          address_line?: string
          city?: string
          created_at?: string
          id?: string
          is_active?: boolean
          kind?: Database["public"]["Enums"]["operational_location_kind"]
          lat?: number | null
          lng?: number | null
          name?: string
          pin_code?: string
          state?: string
          updated_at?: string
        }
        Relationships: []
      }
      order_confirmation_challenges: {
        Row: {
          confirmed_at: string | null
          created_at: string
          expires_at: string
          id: string
          order_id: string
          otp_hash: string | null
          payment_method_intent:
            | Database["public"]["Enums"]["payment_method_intent"]
            | null
          status: Database["public"]["Enums"]["assisted_confirmation_status"]
          token: string
          updated_at: string
        }
        Insert: {
          confirmed_at?: string | null
          created_at?: string
          expires_at: string
          id?: string
          order_id: string
          otp_hash?: string | null
          payment_method_intent?:
            | Database["public"]["Enums"]["payment_method_intent"]
            | null
          status?: Database["public"]["Enums"]["assisted_confirmation_status"]
          token: string
          updated_at?: string
        }
        Update: {
          confirmed_at?: string | null
          created_at?: string
          expires_at?: string
          id?: string
          order_id?: string
          otp_hash?: string | null
          payment_method_intent?:
            | Database["public"]["Enums"]["payment_method_intent"]
            | null
          status?: Database["public"]["Enums"]["assisted_confirmation_status"]
          token?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_confirmation_challenges_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      order_events: {
        Row: {
          actor_profile_id: string | null
          actor_role: Database["public"]["Enums"]["staff_role"] | null
          created_at: string
          from_status: Database["public"]["Enums"]["order_status"] | null
          id: string
          note: string | null
          order_id: string
          to_status: Database["public"]["Enums"]["order_status"]
        }
        Insert: {
          actor_profile_id?: string | null
          actor_role?: Database["public"]["Enums"]["staff_role"] | null
          created_at?: string
          from_status?: Database["public"]["Enums"]["order_status"] | null
          id?: string
          note?: string | null
          order_id: string
          to_status: Database["public"]["Enums"]["order_status"]
        }
        Update: {
          actor_profile_id?: string | null
          actor_role?: Database["public"]["Enums"]["staff_role"] | null
          created_at?: string
          from_status?: Database["public"]["Enums"]["order_status"] | null
          id?: string
          note?: string | null
          order_id?: string
          to_status?: Database["public"]["Enums"]["order_status"]
        }
        Relationships: [
          {
            foreignKeyName: "order_events_actor_profile_id_fkey"
            columns: ["actor_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_events_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      order_lines: {
        Row: {
          agreed_unit_price: number
          created_at: string
          id: string
          line_total: number
          order_id: string
          product_name_snapshot: string
          quantity: number
          selling_unit_snapshot: string
          sku_code_snapshot: string
          sku_id: string
          sku_name_snapshot: string
          specification_snapshot: string | null
          updated_at: string
        }
        Insert: {
          agreed_unit_price: number
          created_at?: string
          id?: string
          line_total: number
          order_id: string
          product_name_snapshot: string
          quantity: number
          selling_unit_snapshot: string
          sku_code_snapshot: string
          sku_id: string
          sku_name_snapshot: string
          specification_snapshot?: string | null
          updated_at?: string
        }
        Update: {
          agreed_unit_price?: number
          created_at?: string
          id?: string
          line_total?: number
          order_id?: string
          product_name_snapshot?: string
          quantity?: number
          selling_unit_snapshot?: string
          sku_code_snapshot?: string
          sku_id?: string
          sku_name_snapshot?: string
          specification_snapshot?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_lines_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_lines_sku_id_fkey"
            columns: ["sku_id"]
            isOneToOne: false
            referencedRelation: "skus"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          adjustments: number
          created_at: string
          created_by_profile_id: string
          currency: string
          expected_delivery_at: string | null
          id: string
          payment_id: string | null
          sale_id: string | null
          service_area_id: string
          shop_id: string
          source: Database["public"]["Enums"]["order_source"]
          status: Database["public"]["Enums"]["order_status"]
          subtotal: number
          total: number
          updated_at: string
        }
        Insert: {
          adjustments?: number
          created_at?: string
          created_by_profile_id: string
          currency?: string
          expected_delivery_at?: string | null
          id?: string
          payment_id?: string | null
          sale_id?: string | null
          service_area_id: string
          shop_id: string
          source: Database["public"]["Enums"]["order_source"]
          status?: Database["public"]["Enums"]["order_status"]
          subtotal?: number
          total?: number
          updated_at?: string
        }
        Update: {
          adjustments?: number
          created_at?: string
          created_by_profile_id?: string
          currency?: string
          expected_delivery_at?: string | null
          id?: string
          payment_id?: string | null
          sale_id?: string | null
          service_area_id?: string
          shop_id?: string
          source?: Database["public"]["Enums"]["order_source"]
          status?: Database["public"]["Enums"]["order_status"]
          subtotal?: number
          total?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "orders_created_by_profile_id_fkey"
            columns: ["created_by_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_payment_id_fkey"
            columns: ["payment_id"]
            isOneToOne: false
            referencedRelation: "payments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_sale_id_fkey"
            columns: ["sale_id"]
            isOneToOne: true
            referencedRelation: "sales"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_service_area_id_fkey"
            columns: ["service_area_id"]
            isOneToOne: false
            referencedRelation: "service_areas"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_shop_id_fkey"
            columns: ["shop_id"]
            isOneToOne: false
            referencedRelation: "shops"
            referencedColumns: ["id"]
          },
        ]
      }
      payment_events: {
        Row: {
          actor_profile_id: string | null
          actor_role: Database["public"]["Enums"]["staff_role"] | null
          created_at: string
          from_status: Database["public"]["Enums"]["payment_status"] | null
          id: string
          note: string | null
          payment_id: string
          to_status: Database["public"]["Enums"]["payment_status"]
        }
        Insert: {
          actor_profile_id?: string | null
          actor_role?: Database["public"]["Enums"]["staff_role"] | null
          created_at?: string
          from_status?: Database["public"]["Enums"]["payment_status"] | null
          id?: string
          note?: string | null
          payment_id: string
          to_status: Database["public"]["Enums"]["payment_status"]
        }
        Update: {
          actor_profile_id?: string | null
          actor_role?: Database["public"]["Enums"]["staff_role"] | null
          created_at?: string
          from_status?: Database["public"]["Enums"]["payment_status"] | null
          id?: string
          note?: string | null
          payment_id?: string
          to_status?: Database["public"]["Enums"]["payment_status"]
        }
        Relationships: [
          {
            foreignKeyName: "payment_events_actor_profile_id_fkey"
            columns: ["actor_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payment_events_payment_id_fkey"
            columns: ["payment_id"]
            isOneToOne: false
            referencedRelation: "payments"
            referencedColumns: ["id"]
          },
        ]
      }
      payments: {
        Row: {
          amount: number
          collection_method:
            | Database["public"]["Enums"]["payment_collection_method"]
            | null
          created_at: string
          currency: string
          id: string
          method_intent: Database["public"]["Enums"]["payment_method_intent"]
          order_id: string
          paid_at: string | null
          provider_reference: string | null
          status: Database["public"]["Enums"]["payment_status"]
          updated_at: string
        }
        Insert: {
          amount: number
          collection_method?:
            | Database["public"]["Enums"]["payment_collection_method"]
            | null
          created_at?: string
          currency?: string
          id?: string
          method_intent: Database["public"]["Enums"]["payment_method_intent"]
          order_id: string
          paid_at?: string | null
          provider_reference?: string | null
          status?: Database["public"]["Enums"]["payment_status"]
          updated_at?: string
        }
        Update: {
          amount?: number
          collection_method?:
            | Database["public"]["Enums"]["payment_collection_method"]
            | null
          created_at?: string
          currency?: string
          id?: string
          method_intent?: Database["public"]["Enums"]["payment_method_intent"]
          order_id?: string
          paid_at?: string | null
          provider_reference?: string | null
          status?: Database["public"]["Enums"]["payment_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "payments_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: true
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          category_id: string
          created_at: string
          description: string | null
          id: string
          image_urls: string[]
          is_active: boolean
          name: string
          product_type: string
          updated_at: string
        }
        Insert: {
          category_id: string
          created_at?: string
          description?: string | null
          id?: string
          image_urls?: string[]
          is_active?: boolean
          name: string
          product_type: string
          updated_at?: string
        }
        Update: {
          category_id?: string
          created_at?: string
          description?: string | null
          id?: string
          image_urls?: string[]
          is_active?: boolean
          name?: string
          product_type?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "products_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          display_name: string
          id: string
          is_active: boolean
          mobile: string
          roles: Database["public"]["Enums"]["staff_role"][]
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_name: string
          id: string
          is_active?: boolean
          mobile: string
          roles?: Database["public"]["Enums"]["staff_role"][]
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_name?: string
          id?: string
          is_active?: boolean
          mobile?: string
          roles?: Database["public"]["Enums"]["staff_role"][]
          updated_at?: string
        }
        Relationships: []
      }
      route_stops: {
        Row: {
          created_at: string
          id: string
          order_id: string
          route_id: string
          sequence: number
          status: Database["public"]["Enums"]["route_stop_status"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          order_id: string
          route_id: string
          sequence: number
          status?: Database["public"]["Enums"]["route_stop_status"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          order_id?: string
          route_id?: string
          sequence?: number
          status?: Database["public"]["Enums"]["route_stop_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "route_stops_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "route_stops_route_id_fkey"
            columns: ["route_id"]
            isOneToOne: false
            referencedRelation: "delivery_routes"
            referencedColumns: ["id"]
          },
        ]
      }
      sales: {
        Row: {
          converted_at: string
          converted_by_profile_id: string | null
          created_at: string
          currency: string
          discount: number
          id: string
          invoice_number: string
          order_id: string
          status: string
          subtotal: number
          total: number
          updated_at: string
        }
        Insert: {
          converted_at?: string
          converted_by_profile_id?: string | null
          created_at?: string
          currency?: string
          discount?: number
          id?: string
          invoice_number: string
          order_id: string
          status?: string
          subtotal?: number
          total?: number
          updated_at?: string
        }
        Update: {
          converted_at?: string
          converted_by_profile_id?: string | null
          created_at?: string
          currency?: string
          discount?: number
          id?: string
          invoice_number?: string
          order_id?: string
          status?: string
          subtotal?: number
          total?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sales_converted_by_profile_id_fkey"
            columns: ["converted_by_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: true
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      sale_items: {
        Row: {
          created_at: string
          discount: number
          id: string
          line_total: number
          order_line_id: string | null
          product_name: string
          quantity: number
          sale_id: string
          sku_code: string
          sku_id: string | null
          sku_name: string
          unit_price: number
        }
        Insert: {
          created_at?: string
          discount?: number
          id?: string
          line_total: number
          order_line_id?: string | null
          product_name: string
          quantity: number
          sale_id: string
          sku_code: string
          sku_id?: string | null
          sku_name: string
          unit_price: number
        }
        Update: {
          created_at?: string
          discount?: number
          id?: string
          line_total?: number
          order_line_id?: string | null
          product_name?: string
          quantity?: number
          sale_id?: string
          sku_code?: string
          sku_id?: string | null
          sku_name?: string
          unit_price?: number
        }
        Relationships: [
          {
            foreignKeyName: "sale_items_order_line_id_fkey"
            columns: ["order_line_id"]
            isOneToOne: false
            referencedRelation: "order_lines"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sale_items_sale_id_fkey"
            columns: ["sale_id"]
            isOneToOne: false
            referencedRelation: "sales"
            referencedColumns: ["id"]
          },
        ]
      }
      sales_payments: {
        Row: {
          amount: number
          collected_at: string | null
          created_at: string
          id: string
          payment_id: string | null
          sale_id: string
          status: string
        }
        Insert: {
          amount?: number
          collected_at?: string | null
          created_at?: string
          id?: string
          payment_id?: string | null
          sale_id: string
          status?: string
        }
        Update: {
          amount?: number
          collected_at?: string | null
          created_at?: string
          id?: string
          payment_id?: string | null
          sale_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "sales_payments_payment_id_fkey"
            columns: ["payment_id"]
            isOneToOne: false
            referencedRelation: "payments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_payments_sale_id_fkey"
            columns: ["sale_id"]
            isOneToOne: true
            referencedRelation: "sales"
            referencedColumns: ["id"]
          },
        ]
      }
      service_areas: {
        Row: {
          created_at: string
          description: string | null
          display_order: number
          id: string
          is_active: boolean
          name: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          display_order?: number
          id?: string
          is_active?: boolean
          name: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          display_order?: number
          id?: string
          is_active?: boolean
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      serviceability_rules: {
        Row: {
          config: Json
          created_at: string
          id: string
          is_active: boolean
          rule_type: Database["public"]["Enums"]["serviceability_rule_type"]
          service_area_id: string
          updated_at: string
        }
        Insert: {
          config?: Json
          created_at?: string
          id?: string
          is_active?: boolean
          rule_type: Database["public"]["Enums"]["serviceability_rule_type"]
          service_area_id: string
          updated_at?: string
        }
        Update: {
          config?: Json
          created_at?: string
          id?: string
          is_active?: boolean
          rule_type?: Database["public"]["Enums"]["serviceability_rule_type"]
          service_area_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "serviceability_rules_service_area_id_fkey"
            columns: ["service_area_id"]
            isOneToOne: false
            referencedRelation: "service_areas"
            referencedColumns: ["id"]
          },
        ]
      }
      shop_auth_links: {
        Row: {
          auth_user_id: string
          id: string
          linked_at: string
          shop_id: string
        }
        Insert: {
          auth_user_id: string
          id?: string
          linked_at?: string
          shop_id: string
        }
        Update: {
          auth_user_id?: string
          id?: string
          linked_at?: string
          shop_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "shop_auth_links_shop_id_fkey"
            columns: ["shop_id"]
            isOneToOne: false
            referencedRelation: "shops"
            referencedColumns: ["id"]
          },
        ]
      }
      shop_contacts: {
        Row: {
          created_at: string
          email: string | null
          id: string
          is_primary: boolean
          mobile: string
          name: string
          shop_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          email?: string | null
          id?: string
          is_primary?: boolean
          mobile: string
          name: string
          shop_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          email?: string | null
          id?: string
          is_primary?: boolean
          mobile?: string
          name?: string
          shop_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "shop_contacts_shop_id_fkey"
            columns: ["shop_id"]
            isOneToOne: false
            referencedRelation: "shops"
            referencedColumns: ["id"]
          },
        ]
      }
      shop_invitations: {
        Row: {
          created_at: string
          expires_at: string
          id: string
          mobile: string
          sent_at: string
          shop_id: string
          status: Database["public"]["Enums"]["shop_invitation_status"]
          token: string
        }
        Insert: {
          created_at?: string
          expires_at: string
          id?: string
          mobile: string
          sent_at?: string
          shop_id: string
          status?: Database["public"]["Enums"]["shop_invitation_status"]
          token: string
        }
        Update: {
          created_at?: string
          expires_at?: string
          id?: string
          mobile?: string
          sent_at?: string
          shop_id?: string
          status?: Database["public"]["Enums"]["shop_invitation_status"]
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "shop_invitations_shop_id_fkey"
            columns: ["shop_id"]
            isOneToOne: false
            referencedRelation: "shops"
            referencedColumns: ["id"]
          },
        ]
      }
      shop_salesman_assignments: {
        Row: {
          assigned_by_profile_id: string | null
          created_at: string
          effective_from: string
          effective_to: string | null
          id: string
          reason: string | null
          salesman_profile_id: string
          shop_id: string
          updated_at: string
        }
        Insert: {
          assigned_by_profile_id?: string | null
          created_at?: string
          effective_from?: string
          effective_to?: string | null
          id?: string
          reason?: string | null
          salesman_profile_id: string
          shop_id: string
          updated_at?: string
        }
        Update: {
          assigned_by_profile_id?: string | null
          created_at?: string
          effective_from?: string
          effective_to?: string | null
          id?: string
          reason?: string | null
          salesman_profile_id?: string
          shop_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "shop_salesman_assignments_assigned_by_profile_id_fkey"
            columns: ["assigned_by_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shop_salesman_assignments_salesman_profile_id_fkey"
            columns: ["salesman_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shop_salesman_assignments_shop_id_fkey"
            columns: ["shop_id"]
            isOneToOne: false
            referencedRelation: "shops"
            referencedColumns: ["id"]
          },
        ]
      }
      shops: {
        Row: {
          assigned_salesman_profile_id: string | null
          created_at: string
          delivery_address_line: string
          delivery_city: string
          delivery_lat: number | null
          delivery_lng: number | null
          delivery_pin_code: string
          delivery_state: string
          id: string
          is_active: boolean
          legal_name: string | null
          lifecycle_status: Database["public"]["Enums"]["shop_lifecycle_status"]
          service_area_id: string | null
          trade_name: string
          updated_at: string
        }
        Insert: {
          assigned_salesman_profile_id?: string | null
          created_at?: string
          delivery_address_line: string
          delivery_city: string
          delivery_lat?: number | null
          delivery_lng?: number | null
          delivery_pin_code: string
          delivery_state: string
          id?: string
          is_active?: boolean
          legal_name?: string | null
          lifecycle_status?: Database["public"]["Enums"]["shop_lifecycle_status"]
          service_area_id?: string | null
          trade_name: string
          updated_at?: string
        }
        Update: {
          assigned_salesman_profile_id?: string | null
          created_at?: string
          delivery_address_line?: string
          delivery_city?: string
          delivery_lat?: number | null
          delivery_lng?: number | null
          delivery_pin_code?: string
          delivery_state?: string
          id?: string
          is_active?: boolean
          legal_name?: string | null
          lifecycle_status?: Database["public"]["Enums"]["shop_lifecycle_status"]
          service_area_id?: string | null
          trade_name?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "shops_assigned_salesman_profile_id_fkey"
            columns: ["assigned_salesman_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shops_service_area_id_fkey"
            columns: ["service_area_id"]
            isOneToOne: false
            referencedRelation: "service_areas"
            referencedColumns: ["id"]
          },
        ]
      }
      sku_prices: {
        Row: {
          created_at: string
          currency: string
          effective_from: string
          effective_to: string | null
          id: string
          recorded_by_profile_id: string | null
          sku_id: string
          trade_price: number
        }
        Insert: {
          created_at?: string
          currency?: string
          effective_from?: string
          effective_to?: string | null
          id?: string
          recorded_by_profile_id?: string | null
          sku_id: string
          trade_price: number
        }
        Update: {
          created_at?: string
          currency?: string
          effective_from?: string
          effective_to?: string | null
          id?: string
          recorded_by_profile_id?: string | null
          sku_id?: string
          trade_price?: number
        }
        Relationships: [
          {
            foreignKeyName: "sku_prices_recorded_by_profile_id_fkey"
            columns: ["recorded_by_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sku_prices_sku_id_fkey"
            columns: ["sku_id"]
            isOneToOne: false
            referencedRelation: "skus"
            referencedColumns: ["id"]
          },
        ]
      }
      skus: {
        Row: {
          created_at: string
          grade: string | null
          id: string
          is_active: boolean
          moq: number
          name: string
          net_quantity: number | null
          net_quantity_unit: string | null
          packs_per_carton: number | null
          product_id: string
          product_type: string
          quantity_step: number
          selling_unit: string
          sku_code: string
          specification: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          grade?: string | null
          id?: string
          is_active?: boolean
          moq?: number
          name: string
          net_quantity?: number | null
          net_quantity_unit?: string | null
          packs_per_carton?: number | null
          product_id: string
          product_type: string
          quantity_step?: number
          selling_unit: string
          sku_code: string
          specification?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          grade?: string | null
          id?: string
          is_active?: boolean
          moq?: number
          name?: string
          net_quantity?: number | null
          net_quantity_unit?: string | null
          packs_per_carton?: number | null
          product_id?: string
          product_type?: string
          quantity_step?: number
          selling_unit?: string
          sku_code?: string
          specification?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "skus_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      stock_reservations: {
        Row: {
          created_at: string
          id: string
          operational_location_id: string
          order_id: string
          quantity: number
          sku_id: string
          status: Database["public"]["Enums"]["stock_reservation_status"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          operational_location_id: string
          order_id: string
          quantity: number
          sku_id: string
          status?: Database["public"]["Enums"]["stock_reservation_status"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          operational_location_id?: string
          order_id?: string
          quantity?: number
          sku_id?: string
          status?: Database["public"]["Enums"]["stock_reservation_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "stock_reservations_operational_location_id_fkey"
            columns: ["operational_location_id"]
            isOneToOne: false
            referencedRelation: "operational_locations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_reservations_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_reservations_sku_id_fkey"
            columns: ["sku_id"]
            isOneToOne: false
            referencedRelation: "skus"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      attach_updated_at_trigger: {
        Args: { p_table: unknown }
        Returns: undefined
      }
      can_read_order: { Args: { p_order_id: string }; Returns: boolean }
      can_read_shop: { Args: { p_shop_id: string }; Returns: boolean }
      current_profile_id: { Args: never; Returns: string }
      customer_shop_ids: { Args: never; Returns: string[] }
      delivery_route_ids: { Args: never; Returns: string[] }
      is_admin: { Args: never; Returns: boolean }
      is_order_confirmed_or_later: {
        Args: { p_status: Database["public"]["Enums"]["order_status"] }
        Returns: boolean
      }
      normalize_mobile: { Args: { p_mobile: string }; Returns: string }
      profile_has_role: {
        Args: { p_role: Database["public"]["Enums"]["staff_role"] }
        Returns: boolean
      }
      salesman_shop_ids: { Args: never; Returns: string[] }
    }
    Enums: {
      assisted_confirmation_status:
        | "PENDING"
        | "CUSTOMER_CONFIRMED"
        | "CUSTOMER_REQUESTED_CHANGES"
        | "CUSTOMER_REJECTED"
        | "EXPIRED"
      delivery_failure_reason:
        | "CUSTOMER_UNAVAILABLE"
        | "SHOP_CLOSED"
        | "PAYMENT_NOT_AVAILABLE"
        | "CUSTOMER_REQUESTED_CREDIT"
        | "CUSTOMER_REFUSED_ORDER"
        | "ADDRESS_LOCATION_ISSUE"
        | "DAMAGED_ORDER_ISSUE"
        | "OTHER"
      delivery_route_status:
        | "DRAFT"
        | "PLANNED"
        | "IN_PROGRESS"
        | "COMPLETED"
        | "CANCELLED"
      inventory_movement_type:
        | "RECEIPT"
        | "ORDER_DISPATCH"
        | "DAMAGE"
        | "RETURN"
        | "ADMIN_ADJUSTMENT"
      operational_location_kind: "OPS_BASE" | "WAREHOUSE" | "OTHER"
      order_source: "CUSTOMER_SELF_SERVE" | "SALESMAN_ASSISTED"
      order_status:
        | "DRAFT_ASSISTED"
        | "AWAITING_CUSTOMER_CONFIRMATION"
        | "CONFIRMED"
        | "STOCK_RESERVED"
        | "PROCESSING"
        | "READY_FOR_DISPATCH"
        | "ASSIGNED_TO_ROUTE"
        | "OUT_FOR_DELIVERY"
        | "DELIVERED"
        | "DELIVERY_FAILED"
        | "CANCELLED"
      payment_collection_method:
        | "ONLINE_GATEWAY"
        | "CASH_ON_DELIVERY"
        | "UPI_ON_DELIVERY"
        | "CARD_ON_DELIVERY"
        | "OTHER"
      payment_method_intent: "PAY_ONLINE_NOW" | "PAY_ON_DELIVERY"
      payment_status:
        | "UNPAID"
        | "PAYMENT_PENDING"
        | "PAID"
        | "FAILED"
        | "REFUNDED"
      route_stop_status:
        | "PENDING"
        | "IN_PROGRESS"
        | "COMPLETED"
        | "FAILED"
        | "SKIPPED"
      serviceability_rule_type: "PIN_CODE" | "ADMIN_AREA" | "POLYGON"
      shop_invitation_status: "PENDING" | "ACCEPTED" | "EXPIRED" | "REVOKED"
      shop_lifecycle_status:
        | "LEAD"
        | "INVITED"
        | "ACTIVATED"
        | "FIRST_ORDER"
        | "REPEAT_CUSTOMER"
        | "INACTIVE_OR_FOLLOW_UP"
      staff_role: "CUSTOMER" | "SALESMAN" | "DELIVERY" | "ADMIN"
      stock_reservation_status:
        | "PENDING"
        | "RESERVED"
        | "RELEASED"
        | "FULFILLED"
        | "FAILED"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  storage: {
    Tables: {
      buckets: {
        Row: {
          allowed_mime_types: string[] | null
          avif_autodetection: boolean | null
          created_at: string | null
          file_size_limit: number | null
          id: string
          name: string
          owner: string | null
          owner_id: string | null
          public: boolean | null
          type: Database["storage"]["Enums"]["buckettype"]
          updated_at: string | null
        }
        Insert: {
          allowed_mime_types?: string[] | null
          avif_autodetection?: boolean | null
          created_at?: string | null
          file_size_limit?: number | null
          id: string
          name: string
          owner?: string | null
          owner_id?: string | null
          public?: boolean | null
          type?: Database["storage"]["Enums"]["buckettype"]
          updated_at?: string | null
        }
        Update: {
          allowed_mime_types?: string[] | null
          avif_autodetection?: boolean | null
          created_at?: string | null
          file_size_limit?: number | null
          id?: string
          name?: string
          owner?: string | null
          owner_id?: string | null
          public?: boolean | null
          type?: Database["storage"]["Enums"]["buckettype"]
          updated_at?: string | null
        }
        Relationships: []
      }
      buckets_analytics: {
        Row: {
          created_at: string
          deleted_at: string | null
          format: string
          id: string
          name: string
          type: Database["storage"]["Enums"]["buckettype"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          deleted_at?: string | null
          format?: string
          id?: string
          name: string
          type?: Database["storage"]["Enums"]["buckettype"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          deleted_at?: string | null
          format?: string
          id?: string
          name?: string
          type?: Database["storage"]["Enums"]["buckettype"]
          updated_at?: string
        }
        Relationships: []
      }
      buckets_vectors: {
        Row: {
          created_at: string
          id: string
          type: Database["storage"]["Enums"]["buckettype"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          id: string
          type?: Database["storage"]["Enums"]["buckettype"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          type?: Database["storage"]["Enums"]["buckettype"]
          updated_at?: string
        }
        Relationships: []
      }
      iceberg_namespaces: {
        Row: {
          bucket_name: string
          catalog_id: string
          created_at: string
          id: string
          metadata: Json
          name: string
          updated_at: string
        }
        Insert: {
          bucket_name: string
          catalog_id: string
          created_at?: string
          id?: string
          metadata?: Json
          name: string
          updated_at?: string
        }
        Update: {
          bucket_name?: string
          catalog_id?: string
          created_at?: string
          id?: string
          metadata?: Json
          name?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "iceberg_namespaces_catalog_id_fkey"
            columns: ["catalog_id"]
            isOneToOne: false
            referencedRelation: "buckets_analytics"
            referencedColumns: ["id"]
          },
        ]
      }
      iceberg_tables: {
        Row: {
          bucket_name: string
          catalog_id: string
          created_at: string
          id: string
          location: string
          name: string
          namespace_id: string
          remote_table_id: string | null
          shard_id: string | null
          shard_key: string | null
          updated_at: string
        }
        Insert: {
          bucket_name: string
          catalog_id: string
          created_at?: string
          id?: string
          location: string
          name: string
          namespace_id: string
          remote_table_id?: string | null
          shard_id?: string | null
          shard_key?: string | null
          updated_at?: string
        }
        Update: {
          bucket_name?: string
          catalog_id?: string
          created_at?: string
          id?: string
          location?: string
          name?: string
          namespace_id?: string
          remote_table_id?: string | null
          shard_id?: string | null
          shard_key?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "iceberg_tables_catalog_id_fkey"
            columns: ["catalog_id"]
            isOneToOne: false
            referencedRelation: "buckets_analytics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "iceberg_tables_namespace_id_fkey"
            columns: ["namespace_id"]
            isOneToOne: false
            referencedRelation: "iceberg_namespaces"
            referencedColumns: ["id"]
          },
        ]
      }
      migrations: {
        Row: {
          executed_at: string | null
          hash: string
          id: number
          name: string
        }
        Insert: {
          executed_at?: string | null
          hash: string
          id: number
          name: string
        }
        Update: {
          executed_at?: string | null
          hash?: string
          id?: number
          name?: string
        }
        Relationships: []
      }
      objects: {
        Row: {
          bucket_id: string | null
          created_at: string | null
          id: string
          last_accessed_at: string | null
          metadata: Json | null
          name: string | null
          owner: string | null
          owner_id: string | null
          path_tokens: string[] | null
          updated_at: string | null
          user_metadata: Json | null
          version: string | null
        }
        Insert: {
          bucket_id?: string | null
          created_at?: string | null
          id?: string
          last_accessed_at?: string | null
          metadata?: Json | null
          name?: string | null
          owner?: string | null
          owner_id?: string | null
          path_tokens?: string[] | null
          updated_at?: string | null
          user_metadata?: Json | null
          version?: string | null
        }
        Update: {
          bucket_id?: string | null
          created_at?: string | null
          id?: string
          last_accessed_at?: string | null
          metadata?: Json | null
          name?: string | null
          owner?: string | null
          owner_id?: string | null
          path_tokens?: string[] | null
          updated_at?: string | null
          user_metadata?: Json | null
          version?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "objects_bucketId_fkey"
            columns: ["bucket_id"]
            isOneToOne: false
            referencedRelation: "buckets"
            referencedColumns: ["id"]
          },
        ]
      }
      s3_multipart_uploads: {
        Row: {
          bucket_id: string
          created_at: string
          id: string
          in_progress_size: number
          key: string
          metadata: Json | null
          owner_id: string | null
          upload_signature: string
          user_metadata: Json | null
          version: string
        }
        Insert: {
          bucket_id: string
          created_at?: string
          id: string
          in_progress_size?: number
          key: string
          metadata?: Json | null
          owner_id?: string | null
          upload_signature: string
          user_metadata?: Json | null
          version: string
        }
        Update: {
          bucket_id?: string
          created_at?: string
          id?: string
          in_progress_size?: number
          key?: string
          metadata?: Json | null
          owner_id?: string | null
          upload_signature?: string
          user_metadata?: Json | null
          version?: string
        }
        Relationships: [
          {
            foreignKeyName: "s3_multipart_uploads_bucket_id_fkey"
            columns: ["bucket_id"]
            isOneToOne: false
            referencedRelation: "buckets"
            referencedColumns: ["id"]
          },
        ]
      }
      s3_multipart_uploads_parts: {
        Row: {
          bucket_id: string
          created_at: string
          etag: string
          id: string
          key: string
          owner_id: string | null
          part_number: number
          size: number
          upload_id: string
          version: string
        }
        Insert: {
          bucket_id: string
          created_at?: string
          etag: string
          id?: string
          key: string
          owner_id?: string | null
          part_number: number
          size?: number
          upload_id: string
          version: string
        }
        Update: {
          bucket_id?: string
          created_at?: string
          etag?: string
          id?: string
          key?: string
          owner_id?: string | null
          part_number?: number
          size?: number
          upload_id?: string
          version?: string
        }
        Relationships: [
          {
            foreignKeyName: "s3_multipart_uploads_parts_bucket_id_fkey"
            columns: ["bucket_id"]
            isOneToOne: false
            referencedRelation: "buckets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "s3_multipart_uploads_parts_upload_id_fkey"
            columns: ["upload_id"]
            isOneToOne: false
            referencedRelation: "s3_multipart_uploads"
            referencedColumns: ["id"]
          },
        ]
      }
      vector_indexes: {
        Row: {
          bucket_id: string
          created_at: string
          data_type: string
          dimension: number
          distance_metric: string
          id: string
          metadata_configuration: Json | null
          name: string
          updated_at: string
        }
        Insert: {
          bucket_id: string
          created_at?: string
          data_type: string
          dimension: number
          distance_metric: string
          id?: string
          metadata_configuration?: Json | null
          name: string
          updated_at?: string
        }
        Update: {
          bucket_id?: string
          created_at?: string
          data_type?: string
          dimension?: number
          distance_metric?: string
          id?: string
          metadata_configuration?: Json | null
          name?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "vector_indexes_bucket_id_fkey"
            columns: ["bucket_id"]
            isOneToOne: false
            referencedRelation: "buckets_vectors"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      allow_any_operation: {
        Args: { expected_operations: string[] }
        Returns: boolean
      }
      allow_only_operation: {
        Args: { expected_operation: string }
        Returns: boolean
      }
      can_insert_object: {
        Args: { bucketid: string; metadata: Json; name: string; owner: string }
        Returns: undefined
      }
      extension: { Args: { name: string }; Returns: string }
      filename: { Args: { name: string }; Returns: string }
      foldername: { Args: { name: string }; Returns: string[] }
      get_common_prefix: {
        Args: { p_delimiter: string; p_key: string; p_prefix: string }
        Returns: string
      }
      get_size_by_bucket: {
        Args: never
        Returns: {
          bucket_id: string
          size: number
        }[]
      }
      list_multipart_uploads_with_delimiter: {
        Args: {
          bucket_id: string
          delimiter_param: string
          max_keys?: number
          next_key_token?: string
          next_upload_token?: string
          prefix_param: string
        }
        Returns: {
          created_at: string
          id: string
          key: string
        }[]
      }
      list_objects_with_delimiter: {
        Args: {
          _bucket_id: string
          delimiter_param: string
          max_keys?: number
          next_token?: string
          prefix_param: string
          sort_order?: string
          start_after?: string
        }
        Returns: {
          created_at: string
          id: string
          last_accessed_at: string
          metadata: Json
          name: string
          updated_at: string
        }[]
      }
      operation: { Args: never; Returns: string }
      search: {
        Args: {
          bucketname: string
          levels?: number
          limits?: number
          offsets?: number
          prefix: string
          search?: string
          sortcolumn?: string
          sortorder?: string
        }
        Returns: {
          created_at: string
          id: string
          last_accessed_at: string
          metadata: Json
          name: string
          updated_at: string
        }[]
      }
      search_by_timestamp: {
        Args: {
          p_bucket_id: string
          p_level: number
          p_limit: number
          p_prefix: string
          p_sort_column: string
          p_sort_column_after: string
          p_sort_order: string
          p_start_after: string
        }
        Returns: {
          created_at: string
          id: string
          key: string
          last_accessed_at: string
          metadata: Json
          name: string
          updated_at: string
        }[]
      }
      search_v2: {
        Args: {
          bucket_name: string
          levels?: number
          limits?: number
          prefix: string
          sort_column?: string
          sort_column_after?: string
          sort_order?: string
          start_after?: string
        }
        Returns: {
          created_at: string
          id: string
          key: string
          last_accessed_at: string
          metadata: Json
          name: string
          updated_at: string
        }[]
      }
    }
    Enums: {
      buckettype: "STANDARD" | "ANALYTICS" | "VECTOR"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      assisted_confirmation_status: [
        "PENDING",
        "CUSTOMER_CONFIRMED",
        "CUSTOMER_REQUESTED_CHANGES",
        "CUSTOMER_REJECTED",
        "EXPIRED",
      ],
      delivery_failure_reason: [
        "CUSTOMER_UNAVAILABLE",
        "SHOP_CLOSED",
        "PAYMENT_NOT_AVAILABLE",
        "CUSTOMER_REQUESTED_CREDIT",
        "CUSTOMER_REFUSED_ORDER",
        "ADDRESS_LOCATION_ISSUE",
        "DAMAGED_ORDER_ISSUE",
        "OTHER",
      ],
      delivery_route_status: [
        "DRAFT",
        "PLANNED",
        "IN_PROGRESS",
        "COMPLETED",
        "CANCELLED",
      ],
      inventory_movement_type: [
        "RECEIPT",
        "ORDER_DISPATCH",
        "DAMAGE",
        "RETURN",
        "ADMIN_ADJUSTMENT",
      ],
      operational_location_kind: ["OPS_BASE", "WAREHOUSE", "OTHER"],
      order_source: ["CUSTOMER_SELF_SERVE", "SALESMAN_ASSISTED"],
      order_status: [
        "DRAFT_ASSISTED",
        "AWAITING_CUSTOMER_CONFIRMATION",
        "CONFIRMED",
        "STOCK_RESERVED",
        "PROCESSING",
        "READY_FOR_DISPATCH",
        "ASSIGNED_TO_ROUTE",
        "OUT_FOR_DELIVERY",
        "DELIVERED",
        "DELIVERY_FAILED",
        "CANCELLED",
      ],
      payment_collection_method: [
        "ONLINE_GATEWAY",
        "CASH_ON_DELIVERY",
        "UPI_ON_DELIVERY",
        "CARD_ON_DELIVERY",
        "OTHER",
      ],
      payment_method_intent: ["PAY_ONLINE_NOW", "PAY_ON_DELIVERY"],
      payment_status: [
        "UNPAID",
        "PAYMENT_PENDING",
        "PAID",
        "FAILED",
        "REFUNDED",
      ],
      route_stop_status: [
        "PENDING",
        "IN_PROGRESS",
        "COMPLETED",
        "FAILED",
        "SKIPPED",
      ],
      serviceability_rule_type: ["PIN_CODE", "ADMIN_AREA", "POLYGON"],
      shop_invitation_status: ["PENDING", "ACCEPTED", "EXPIRED", "REVOKED"],
      shop_lifecycle_status: [
        "LEAD",
        "INVITED",
        "ACTIVATED",
        "FIRST_ORDER",
        "REPEAT_CUSTOMER",
        "INACTIVE_OR_FOLLOW_UP",
      ],
      staff_role: ["CUSTOMER", "SALESMAN", "DELIVERY", "ADMIN"],
      stock_reservation_status: [
        "PENDING",
        "RESERVED",
        "RELEASED",
        "FULFILLED",
        "FAILED",
      ],
    },
  },
  storage: {
    Enums: {
      buckettype: ["STANDARD", "ANALYTICS", "VECTOR"],
    },
  },
} as const

